### ISSUE TITLE
Gift Sender Not working

### ISSUE THREAD

**Issue by Coxeroni** [chrisisth/PokemonGo-Automate-Flows#9]
Phone: Pixel 7

When trying to send gifts, I start from the friend list. As a first step of the flow, my friend list is closed and so the subsequent steps don’t do anything. Maybe I didn’t get what "having sent a gift with a preferred sticker" means.

For what it’s worth, opening gifts seems to work fine.

Thanks for your great work, I hope to get the gift sending to work as well :)

Edit: Playing around further, do I need to start at a friend that has **sent** me a gift which is closed/not opened as first step? Or is it enough to start at a friend instead of the friend list?

**Comment by Coxeroni** [comment]
Thanks for the clarification!
I got it to work in the meantime, at least on my secondary phone (Motorola G52). I really got confused by the sticker thing.
On my main phone, a Pixel 7, when starting the script it only opens the trainer status info and does not proceed. Not sure why.

Thanks for your help, the scripts are great!

**Comment by chrisisth** [comment]
Ah okay, this is most likely due to the script failing to press the x button at the bottom of the screen.
I changed this to a simulated press of the back button now as this works too and should be more compatible with different devices. Try it out :)
https://github.com/chrisisth/PokemonGo-Automate-Flows/raw/main/Send%20or%20open%20presents/Send%20presents.flo

**Comment by chrisisth** [comment]
Allright i changed the location of the simulated click on the gift button.
It now should be allright on your device, please try it out :)
https://github.com/chrisisth/PokemonGo-Automate-Flows/raw/main/Send%20or%20open%20presents/Send%20presents.flo

**Comment by Coxeroni** [comment]
Thanks! Seems to be a tough one...
It now hits the present, but doesn't seem to hit the postcard...
There is also 4 or 5 attempts/hits/clicks until the gift is hit, not sure if this is intended.

**Comment by chrisisth** [comment]
Thanks for your feedback :)

I went through the script again and now changed all simulated clicks to be more exact and a bit more to the right and a bit higher than it was before. I really hope this solves the issue.

https://github.com/chrisisth/PokemonGo-Automate-Flows/raw/main/Send%20or%20open%20presents/Send%20presents.flo

**Comment by Coxeroni** [comment]
Works like a charm! Thanks a lot!

One question regarding the stickers:
What is the condition whether stickers are applied or not?
Are they only used when I sent a gift manually with a sticker before using the script?

**Comment by chrisisth** [comment]
They are always applied, but I can create a separate script that doesn’t include this.
When a gift is manually sent with a sticker, it sets that sticker as the first entry in the ‘most recently used’ section of the sticker menu. 
This ensures the appropriate sticker is used when the script is running, because the script will click on that first entry.

**Comment by Coxeroni** [comment]
Interesting. When doing the Send Gifts on my Motorola G52, no stickers are applied 😁
I didn't miss them until now, so that is why I didn't get when/how they will be applied.
So far I only sent stickers to selected persons, but since you normally drown in them, why not send them to everybody 😉

**Comment by chrisisth** [comment]
Hahaha interesting :D now i see the confusion.
If you ever need the script without the stickers just write me 👍
